#########################################################################
############################ Parameters #################################
#########################################################################

# Executor params
slurm:
  project: "naiss2025-22-494"

# Result directory base params
res:
  qc: "results/00-QC"
  trim: "results/01-trimmed"
  decon: "results/02-decontamination"
  mergedSample: "results/03-sample-merged-sr"
  mergedPop: "results/04-pop-merged-sr"
  metagenome: "results/05-metagenomes"
  binning: "results/06-metaWRAP-bins"
  binRef: "results/07-metaWRAP-refined-bins"

# Init params
metadata:
  sr: "doc/metadata-sr.csv"
  lr: "doc/metadata-lr.csv"

references:
  comp:
    fasta: "../MAG-MAYHEM/data/comp_ref/competitive-ref.fasta"
    headers: "doc/hh-headers.txt"
    index: "data/comp_ref/competitive-ref.fasta.gz.bwt"  # optional precomputed index

# Process params
fastqc_raw:
  input: "data/sr-raw/*.fastq.gz"

fastqc_ccs:
  input: "data/hifi-ccs-raw/*.fastq.gz"

trim:
  input: "data/sr-raw/*_R{1,2}_001.fastq.gz"
  avg_qual: 20
  len_req: 36






#########################################################################
########################## Singularity Images ###########################
#########################################################################
# Images are created through seqera (https://seqera.io/)
# QC: Initial read processing and quality control (created 2025-05-15)
#   channels:
#   - conda-forge
#   - bioconda
#   dependencies:
#   - bioconda::bbmap=39.00
#   - bioconda::bwa=0.7.19
#   - bioconda::fastp=0.24.1
#   - bioconda::fastqc=0.12.1
#   - bioconda::minimap2=2.29
#   - bioconda::multiqc=1.28
#   - bioconda::picard=3.4.0
#   - bioconda::samtools=1.20
#   - bioconda::seqkit=2.10.0
#   - conda-forge::pigz=2.8
#
# ALIGN: Aligners and parse tools (created 2025-05-22)
#   channels:
#   - conda-forge
#   - bioconda
#   dependencies:
#   - bioconda::bedtools=2.31.1
#   - bioconda::bwa=0.7.19
#   - bioconda::minimap2=2.29
#   - bioconda::picard=3.4.0
#   - bioconda::samtools=1.20
#   - conda-forge::pigz=2.8
#
# STATS: Sequence statistics programs (created 2025-05-22)
#   channels:
#   - conda-forge
#   - bioconda
#   dependencies:
#   - bioconda::bbmap=39.00
#   - bioconda::biopet-validatefastq=0.1.1
#   - bioconda::seqkit=2.10.0
#
# ASSEMBLY: Metagenome assembler for both short and long reads (created 2025-05-26)
#   channels:
#   - conda-forge
#   - bioconda
#   dependencies:
#   - bioconda::megahit=1.2.9
#   - bioconda::metamdbg=1.1
#########################################################################

images:
  QC: "oras://community.wave.seqera.io/library/bbmap_bwa_fastp_fastqc_pruned:676e8c82ba1c1ecb"
  ALIGN: "oras://community.wave.seqera.io/library/bedtools_bwa_minimap2_picard_pruned:4abd28692b1e99f7"
  STATS: "oras://community.wave.seqera.io/library/bbmap_biopet-validatefastq_seqkit:a1c4fb2615ae72e6"
  ASSEMBLY: "oras://community.wave.seqera.io/library/megahit_metamdbg:6fcef2bb1a0bd3a9"
  #metaWRAP: "https://depot.galaxyproject.org/singularity/metawrap:1.0--0"
  metaWRAP: "./containers/metawrap_final.sif"